unixorn/zsh-quickstart-kit

zsh/.zgen-setup
=> oh-my-zsh renamed colored-man to colored-man-pages

zsh/.zgen-setup
=> Updated .zgen-setup to fix coloured-man-pages plugin

.travis.yml, zsh/.zgen-setup, zsh/.zsh_aliases, zsh/.zsh_functions, zsh/.zshrc
This adds automatic updating to zsh-quickstart-kit. This will make it easier for users to get fixes.
=> Add selfupdate capability

Readme.md
* Fixed heading levels in OS section
* Added missing trailing . to some list entries
* Made references to powerline-compatible fonts consistent
=> Update Readme for consistency

zsh/.zshrc
Not a big improvement, but a bit more convenient to me :-)
=> Loop on SSH keys

zsh/.zgen-setup
Hi,
I prefer to have 3rd party repositories in a sub-folder. So I added a variable.
Edit: I forgot to remove the sub-folder when committing - sorry.
Thanks
M.
=> Zgen parent dir

Readme.md
Rename OS X references to macOS
=> Rename OS X to macOS

Readme.md
* Make the plugin list more consistent.
* Add link to bullet-train
* Phrasing tweaks
=> Clean up README.md

zsh/.zshrc
Enable iterm2 integration when present
=> Check for iterm2 integration and source it if present

.zgen-local-plugins-example, Readme.md, zsh/.zgen-setup
Another trivial update, but since I don't know how long-term github's forwarding of old to new owner usernames goes on for, here's a stitch in time just in case. :smiley:
=> update rimraf/k to current origin of supercrabtree/k

zsh/.zshrc
Write the font mode you want to `~/.powerlevel9k_font_mode`.
=> Make it easy to set the font mode for the powerlevel9k prompt

Readme.md, zsh/.zgen-setup
* TOC update
* Wording and formatting cleanups in Readme.md
* Update OS X to macOS in `.zgen-setup`
=> Cleanup readme

LICENSE.txt, zsh/.zgen-setup, zsh/.zsh_aliases
* Update copyright in LICENSE.txt
* Clean up comments
* Update ssh aliases
=> Minor cleanups

Readme.md
* Tweak wording throughout Readme.md
* Add FAQ for removing unwanted aliases
=> Document removing unwanted aliases from plugins

zsh/.zgen-setup, zsh/.zsh_aliases, zsh/.zsh_functions, zsh/.zshrc
* Standardized on single quoting alias text unless doubles are required for variable interpolation
* Added some aliases with - instead of _ to make them easier to type
* Don't use unnecessary `function` keyword
* Update copyright dates
=> Minor zshrc tweaks

Changes.md, zsh/.zshrc
=> Stop stepping on OS-provided $PATH

Readme.md
* Add Victor Mono font link
* Add note that iTerm2 shell integrations will be autoloaded if they're installed
=> Add victor mono font

zsh/.zshrc
Add configuration instructions if p10k hasn't been configured.
=> Update .zshrc for p10k

.circleci/config.yml, Readme.md
* Fix missed bullettrain reference
* Add delay between awesome_bot checks so it doesn't get rate limited during CI tests
=> Missed a bullettrain reference that should be p10k

.zgen-local-plugins-example, Readme.md, zsh/.zgen-setup
* Added fzf-zsh-plugin to the standard plugin set
* Readme updates
=> Add fzf-zsh-plugin to the standard load.

.github/workflows/awesomebot.yml, .github/workflows/superlinter.yml
Use github actions for PR validation
=> Validate with github actions

Readme.md
Add Github build status badge, remove CircleCI.
=> Added GH build status badge

Readme.md
Closes https://github.com/unixorn/zsh-quickstart-kit/issues/95
=> Document dealing with git error

zsh/.zshrc
Closes #98, enables functionality that hasn't been working for a long time - not sure how I missed it.
Thanks @lenart12 for the catch
=> Add missing -o in find command

zsh/.zshrc
I added support for [keychain](https://linux.die.net/man/1/keychain) and fixed a bug I mentioned in #101
=> Suport for keychain

.github/workflows/superlinter.yml, zsh/.zshrc
- Fix bug in `.zshrc.d` handling
- Update superlint configuration
=> Fix issue in .zshrc.d handling

.zgen-local-plugins-example, zsh/.zgen-setup, zsh/.zshrc
Replace zgen commands in dotfiles with new zgenom ones.
=> Zgenom cleanups

zsh/.zshrc
Sometimes I _really_ hate shell syntax.
=> Fix stupid typo introduced in brew fixup

Readme.md
Closes https://github.com/unixorn/zsh-quickstart-kit/issues/127
Thanks @RonanJackson for reporting a fix.
=> Add FAQ answer for completion complaint

Readme.md
Remove issues badge, add awesomebot and superlint badges
=> Remove issues badge, add awesomebot and superlint badges

zsh/.zshrc
=> check if .ssh folder exists and create if not

zsh/.zgen-setup
This PR hides the .zgenom folder from dir listing.
=> Hide .zgenom folder on auto-clone

Readme.md, zsh/.zshrc
Add `update` and `update-plugins` subcommands to `zqs`
- Add `zqs update` that updates the kit and plugins
- Add `zqs update-plugins` that just updates the user's plugins
=> Add zqs subcommands

zsh/.zsh_aliases
This was annoying. Closes #156
=> Fix missing `_`

Readme.md
It still was looking at the master branch
=> Fix last commit badge

zsh/.zshrc
=> Improve homebrew `$PATH` setup

.github/workflows/superlinter.yml, zsh/.zshrc
Update the superlinter configuration to use version 4.
Signed-off-by: Joe Block <jpb@unixorn.net>
=> Update superlinter to use @v4

.github/workflows/superlinter.yml, Readme.md, zsh/.zshrc
- Migrate the OMZ toggle function to a `zqs` command for consistency.
- Minor documentation cleanups
=> Add zqs disable-omz-plugins and enable-omz-plugins commands

Readme.md
Found another source of nerd fonts.
=> Add another nerd font download link

.github/PULL_REQUEST_TEMPLATE.md, LICENSE.txt
- Add PR template
- Update dates in license file
=> Add a PR template and update license dates

Readme.md
Various fixes in `README.md` to increase grammatical correctness.
- add missing articles
- add punctuation
- correct article agreement
- correct spelling
direct paths (`#!/bin/sh` is an allowed exception)
run standalone. No one should have to know if a script was written in bash, python, ruby or
whatever. Not including file extensions makes it easier to rewrite the script in another language
later without having to change every reference to the previous version.
existing commit, and you can find more details about signing off commits on the DCO GitHub action
page [here](https://probot.github.io/apps/dco/)
inline in their code) and by making this PR, I am contributing my changes to the repository 
under the terms of the Apache 2 license.
Signed-off-by: Vladislav Doster …
=> (docs): misc. updates in `Readme.md`

Readme.md
Minor tweak to stow instructions
=> Minor tweak to stow instructions

Readme.md
The git@ link requires additional setup. The https link works automatically!
Updated the link from `git@github.com/unixorn/zsh-quickstart-kit.git` to the newer `https://github.com/unixorn/zsh-quickstart-kit.git`
- [ x Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an allowed exception)
- [x} Scripts _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
=> Updated the link in install instruction

.github/PULL_REQUEST_TEMPLATE.md, zsh/.zgen-setup, zsh/.zsh_aliases, zsh/.zsh_functions, zsh/.zshrc
- Update copyright dates
- Update the deprecation warnings for `.zsh_functions.local` and `.zsh_aliases.local` to include a link to the quickstart documentation for `.zshrc.d` entries and the deadline to switch over.
- Update functions to complain if the binaries they need are missing
=> Update `.zsh_functions` and `.zsh_aliases`

zsh/.zshrc
Adds a small chain to fix support of keychain, which was broken previously.
=> Fixed start of ssh-agent if using keychain

.github/workflows/mega-linter.yml, Readme.md
- Switch from `superlinter` GitHub action to `mega-linter`
- Update badges
Closes https://github.com/unixorn/zsh-quickstart-kit/issues/182
=> Switch to mega-linter

Readme.md
Fix stupid paste error, and commit the superlint badge removal
=> Fix badges

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/awesomebot.yml
Add more 5?? codes to awesomebot ignore list. Better to have false negatives than to have a PR blocked because a webserver somewhere is having temporary issues.
=> Make awesomebot checks more robust

.codeclimate.yml, Readme.md
=> Update readme and codeclimate

Readme.md
Remove `.zsh-completions` reference - we don't include one in the kit, instead users should use entries in `.zshrc.d` which is easier to customize and doesn't require maintaining a fork of the kit.
=> Update symlink instructions

.zsh-quickstart-local-plugins-example, Contributing.md, Readme.md, zsh/.zgen-setup, zsh/.zsh_functions, zsh/.zshrc
- Load `.zsh_functions` before `.zgen_setup` to ensure helper functions are available
- Update toggle file handling to use the new settings functions
- Add a testbranch toggle file to make testing easier.
- Add Contributing.md to the repository
Closes #189
=> Update settings handling for #189

zsh/.zsh_functions, zsh/.zshrc
We need to source shell fragment files in multiple locations, so replace the copy-pasta with a `load-shell-fragments` function.
=> Dedupe shell fragment load code

zsh/.zshrc
Included `ed25519` keys in the `load-our-ssh-keys` function.
not sure how this would qualify
=> add ed25519 to list of managed ssh keys

.gitignore
Add `.idea` and `.vscode` to `.gitignore`
=> Add `.idea` and `.vscode` to `.gitignore`

zsh/.zsh_aliases, zsh/.zshrc
- Add more linuxbrew directories to `$PATH` when present
- Add customization instructions to `.zsh_aliases`
=> Add more linuxbrew directories to `$PATH` when present

Readme.md
Sort the plugin list in Readme.md
=> Sort the plugin list in Readme.md

.github/workflows/mega-linter.yml
Update mega-linter GitHub action to v6
=> Update mega-linter to v6

Readme.md
Per https://github.com/unixorn/zsh-quickstart-kit/issues/205, update instructions on using your own plugins, either in addition to the kit's standard load, or to replace the standard list.
=> Add instructions for adding plugins in `.zshrc.d` files

Readme.md
`brew` can install nerd fonts, so add instructions on how.
=> Add brew install instructions for nerd fonts

.github/FUNDING.yml
Fix mistaken removal of FUNDING.yml
=> Fix FUNDING.yml

zsh/.zsh_aliases, zsh/.zshrc
I was assuming `brew` would always install into `/usr/local`.  Newer installs of brew, particularly on ARM machines, install into `/opt/homebrew`.
- Add checks for `$(brew --prefix)/bin` and `$(brew --prefix)/sbin` in places that we used to just check for `/usr/local/{bin,sbin}`
Closes #217
=> Better support for brew on armbooks

.github/workflows/awesomebot.yml, zsh/.zshrc
- The output of `sw_vers --buildVersion` is a pita to parse. `--productVersion` gives us a nice human-readable form, so we're switching to using that to make the Monterey-or-later check less brittle.
- Ignore ssl errors in awesomebot config - we don't want to block a PR just because some web page is having SSL issues.
Closes #226
=> Bugfix Monterey check

Readme.md
=> Add thanks section

zsh/.zshrc
=> Fixup for [BUG] #236

Readme.md
There's not a standard way of determining a plugin's version, so it isn't easy to pin a specific version of a given plugin.
Add FAQ explaining how to maintain your own copy of an plugin's upstream repository and use tags in it to pin versions.
=> Add FAQ about pinning plugin versions

.github/workflows/dependabot.yml
=> Add dependabot check on our GH actions

Readme.md
- Collapse OS-specific instructions sections
- Update TOC
=> Collapse OS-specific instructions sections

.zsh-quickstart-local-plugins-example, Readme.md, zsh/.zgen-setup
Apple has _different_ non-standard ways to reset the DNS cache depending on what major OS release you're on.
Add `eventi/noreallyjustfuckingstopalready` to the standard plugin list to cope.
=> Apple's DNS resolver is annoying when you want to reset your DNS cache

Readme.md
http://mplus-fonts.osdn.jp/ is not responding, delete link.
=> Delete dead link to mplus-fonts

Readme.md
Readme.md was not displaying lists and links correctly under `<details/>`.  I fixed this by adding newlines between the `<details/>` tags and the interior content. 
Credit to user [SCMX](https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2#code).
Signed-off-by: Jet Lee <gamestar109@live.com>
=> [README] Fix HTML for MacOS and Linux instructions

zsh/.zshrc
Fix typo in ssh-askpass-require->enable-ssh-askpass-require. The fragment file name and the function check for that file name didn't match so it would never ask for the passphrase on the cli in Linux.
This is now working as expected.
Fixes #229, #233
=> [BUG]: fixup enable-ssh-askpass-require

zsh/.zsh_aliases
fixes #296
Signed-off-by: Wuast94 <github@wuast24.de>
=> Fix Grep command
