- zsh/.zgen-setup
The call to load-starter-plugin-list w/ parens broke setup for me.
> Fix inital setup

- zsh/.zsh_functions
Uses zsh native methods to see if a command exists.  This will not show any aliases or functions, however.
> faster, better exists() method

- zsh/.zshrc
Every time this runs for me the pushd call tries to switch to `/Users/xyz//Users/xyz/<actual zshrc location>`.  This little check prevents that from happening.
> don't glom ${HOME} to $(readlink ~/.zshrc)

- zsh/.zshrc
If a plugin aliased ls and ls fails, your customizations would't load.
> Use /bin/ls instead of whatever ls got aliased to

- zsh/.zshrc
Rust's cargo build tool installs to `~/.cargo/bin` by default; make sure
that is in the user's `$PATH` if present.
> Add cargo's bindir to path candidates

- .zgen-local-plugins-example
- Readme.md
- zsh/.zgen-setup
Make it easier for people to start customizations by giving them a `.zgen-local-plugins` file that installs everything the kit does by default. They can change it to meet their needs without having to start from scratch.
> Add template .zgen-local-plugins file

- Readme.md
Per feedback from @dantrevino, Konsole needs to be set to use UTF-8 encoding.
Closes #31
> Add Konsole UTF-8 note

- .codeclimate.yml
Code Climate doesn't like our unordered list entries; disable that check
> Ignore unordered list complaints in markdown check

- Readme.md
- zsh/.zgen-setup
- zsh/.zsh_aliases
- zsh/.zshrc
* Updated copyright notices
* OS X is now called macOS, fix references
* Updated doc comments
* Detailed how to override ZSH options set by the quickstart
* Sorted list of included plugins
* Updated TOC in Readme.md
> Minor text cleanups

- zsh/.zshrc
Hi Joe.
I organize my keys into subfolders.  My `~/.ssh/config` looks like this:
```
Include ~/.ssh/github.com/config
Include ~/.ssh/example.com/config
...
```
This PR changes the ssh key discovery to use `find` for all the keys.
> Allow ssh keys to be discovered in subfolders of ~/.ssh

- Readme.md
Document workaround for `stow` error on macOS. Closes #7.
> Add FAQ section

- zsh/.zshrc
* Update comments accordingly
* Add handlng `.macos_aliases.d` for clarity
* Deal with potential spaces in path to `$HOME`
> Apple renamed OS X to macOS years ago, update

- zsh/.zsh_functions
- zsh/.zshrc
* Update history handling options
* Add completions options
* Explicitly enable INTERACTIVE_COMMENTS
* Move ssh key handling into a `load-our-ssh-keys` function to make it possible to reload ssh keys in a running session conveniently.
* Fix bug where we were trying to load all our ssh private keys every new shell session instead of only when no keys are present in our `ssh-agent` process
* Try to automatically load files suffixed `id_rsa`, `id_dsa` and `id_ecdsa` instead of only the default key names
> Hacktoberfest update to options and ssh key handling

- .zgen-local-plugins-example
- Changes.md
- Readme.md
- zsh/.zgen-setup
- zsh/.zshrc
* Enable zmv by default
* Add option to disable loading oh-my-zsh-defaults by creating `~/.zsh-quickstart-no-omz`
> Enable zmv, allow disabling oh-my-zsh

- zsh/.zshrc
bracketed-paste makes autosuggestion wonky. Fix.
Closes #73
> Deal with bracketed-paste issue

- .zgen-local-plugins-example
- Changes.md
- Readme.md
- zsh/.zgen-setup
- zsh/.zsh_aliases
- zsh/.zsh_functions
Switch default prompt to p10k
* Switch the default prompt to p10k
* Print instructions for how to revert to bullet-train the first time a new session uses p10k
* Add helper functions to make toggling the prompt and whether we load OMZ easier
* Add a few more aliases to baked in functions to make typing them easier
* Update url for bullet-train since the repo path has been changed upstream
* Update the example `.zgen-local-plugins` file
> Make powerlevel10k the default prompt

- Readme.md
- zsh/.zshrc
Users can now disable printing the list of keys by setting `DONT_PRINT_SSH_KEY_LIST` in a file in `~/.zshrc.d`.
I wanted to add the ability to disable without changing the behavior for existing users.
Closes #75.
> Make it possible to disable printing the ssh key list during login

- Readme.md
Have had a couple of complaints about `stow` not working - add details on manually symlinking to readme.
> Add manual symlink instructions

- zsh/.zshrc
Rather than have Oh-My-ZSH update on its own schedule, stay consistent in our behavior and let zgen handle it when it updates the user's other plugins.
Closes #62
> Disable automatic OMZ updates - use zgen's instead

- zsh/.zsh_aliases
- zsh/.zshrc
- Check for brew-install path to `grc.bashrc` if brew is installed instead of assuming `/usr/local/etc/grc.bashrc`
- Update `.zshrc` to tell user where to override the `setopt` settings provided by the quickstart.
> Improve usage of grc

- .zgen-local-plugins-example
- Readme.md
- zsh/.zgen-setup
- zsh/.zshrc
- Update to use autoupdate-zgenom instead of autoupdate-zgen plug
- If `$GOPATH` is defined, add it to `$PATH`
- Add inline comments to README.md describing how to best override kit settings
- Add inline instructions on how to add directories to `$PATH`
- brew doesn't have to be installed in `/usr/local` - use `$(brew --prefix)` instead for $PATH addition
> Update path handling

- zsh/.zshrc
This uses the fingerprint of the key rather than depending on the filename being printed as the output from `ssh-add -l` (which is not always the case).
> Use key fingerprint instead of filename for check

- zsh/.zgen-setup
This commit updates a stale reference to `~/.zgen/init.zsh` in `zsh/.zgen-setup`, to `~/.zgenom/init.zsh`.
Fixes #106
> Update stale reference to ~/.zgen/init.zsh

- zsh/.zsh_functions
Added `function` keyword to explicitly define
functions and prevent alias expansion. Partially resolves issue [15](https://github.com/unixorn/zsh-quickstart-kit/issues/15)
> Added `function` keyword

- Readme.md
- zsh/.zshrc
bash prints `^C` when you're typing a command and control-c to cancel, so it is easy to see it wasn't executed. By default, ZSH doesn't print the `^C`. I like seeing the `^C`, so by default the quickstart now traps `SIGINT` and prints the `^C`.
> Trap sigint and print a ^C

- zsh/.zshrc
Enables the `-q` flag on ssh-add, which silences output for successful operations.
Fixes #119
> Silence output from ssh-add

- zsh/.zshrc
Add readability check before trying to source `~/.keychain/$hostname-sh`
> Make keychain sourcing more resilient

- zsh/.zshrc
Added some more code to start `ssh-agent` only if necessary.
This addresses: https://github.com/unixorn/zsh-quickstart-kit/issues/123
> Added code to start SSH agent only if not running.

- Readme.md
- zsh/.zshrc
- Add warning when `fzf` isn't in `$PATH` (and link to instructions)
- Add fzf install instructions to readme
Closes #122
> Add warning when fzf can't be found in $PATH

- .zsh-quickstart-local-plugins-example
- Readme.md
- zsh/.zgen-setup
Replace `.zgen-local-plugins` with `.zsh-quickstart-local-plugins`, and make `.zsh-quickstart-local-plugins` have precedence if both exist.
> Don't use framework-specific name for plugin override file

- zsh/.zshrc
Fixing a couple of bare `.ssh` that should be `~/.ssh`
Potential fix for #141
> Add missing ~/ to path to .ssh

- zsh/.zshrc
Recent versions of Homebrew are moving to /opt/homebrew, this picks that up
> add brew support in /opt/homebrew

- .github/workflows/superlinter.yml
- zsh/.zshrc
- We've been printing a deprecation warning to use a file inside `.zshrc.d` for six months, remove the load of `.zshrc.local`
- Update `superlinter` configuration now that the default branch has been renamed to `main`
> Remove stale .zshrc.local support

- Readme.md
- zsh/.zshrc
Start adding a `zqs` command to make controlling the kit a little less painful for end users.
- Add `zqs check-for-updates` command
- Add `zqs selfupdate` command
Closes #139
> Add a `zqs` command

- zsh/.zshrc
I've renamed the default branch from `master` to `main`, so make the kit figure out what the default branch is as part of `_update-zsh-quickstart` and switch to it before doing a `git pull`.
Closes #146
> Make quickstart automatically switch to new default branch

- zsh/.zsh_functions
I develop the kit on macOS, and macOS doesn't ship with `watch`.  We now only define the `watch` function when there is no `watch` already in the user's `$PATH`.
Closes #104
> Only define watch function when there is no watch in $PATH

- .zsh-quickstart-local-plugins-example
- zsh/.zgen-setup
Update our plugin list. - the `osx` plugin has been deprecated/renamed in favor of `macos`.
Closes #152
Signed-off-by: Joe Block <jpb@unixorn.net>
> oh-my-zsh has deprecated old osx plugin

- zsh/.zsh_aliases
- If `exa` is installed, use it instead of `ls`.
- Set `EXA_TREE_IGNORE` if the user doesn't already have it set up
- Add `tree` alias to use `exa` if there isn't already a system-installed `tree` command.
> Use exa instead of ls when present

- .github/workflows/awesomebot.yml
Github occasionally pukes up 502 errors for good links when awesomebot is checking the links in readme.md, even with the check interval set to 1 second.
Ignore the 502s, if there's a real issue it'll get found in the next test run and this makes it easier to see if there's a real problem.
> Allow 502s during link checking

- .github/workflows/superlinter.yml
This should hopefully fix the badge in `Readme.md`
> Stop ignoring main branch in superlinter

- zsh/.zsh_aliases
- zsh/.zshrc
We were looking for `exa` before `$PATH` was fully updated, so didn't find it on all systems.
> Set up ls aliases after PATH is fully constructed

- .github/PULL_REQUEST_TEMPLATE.md
- Readme.md
Put commit signing instructions earlier in PR template
> Put commit signing instructions earlier in PR template

- zsh/.zshrc
If the user has already customized `LSCOLORS` or `LS_COLORS`, we should leave their values in place.
> Only set LSCOLORS or LS_COLORS when they're unset

- zsh/.zshrc
Add `_zqs-get-setting-value`, `_zqs-set-setting-value` and `_zqs-purge-setting-value` functions. This is part one of implementing #189 
Next step is to update all the random settings files `zqs` writes to toggle features to use these settings functions
> Start work on standardizing settings reads

- Readme.md
- zsh/.zshrc
We now load shell fragments from the `.zshrc.pre-plugins.d` directory before we start loading plugins.
This is to allow users to set environment variables that control the behavior of their custom plugins before the plugins are loaded.
Enables easy workarounds for #180
> Add `.zshrc.pre-plugins.d` directory handling

- .github/PULL_REQUEST_TEMPLATE.md
- Readme.md
- zsh/.zshrc
Allow users to enable/disable `bindkey` and alias expansion with `zqs-enable-bindkey-handling` and `zqs-disable-bindkey-handling`.
Closes #196
> Enable `bindkey` and alias expansion configuration.

- .zsh-quickstart-local-plugins-example
- Readme.md
- zsh/.zgen-setup
Replace `zsh-users/zsh-syntax-highlighting` with `zdharma-continuum/fast-syntax-highlighting`
`zdharma-continuum/fast-syntax-highlighting` is faster and better at parsing ZSH syntax.
Closes #212
> Update syntax highlighting plugin

- Readme.md
- zsh/.zshrc
Adds `zqs get-setting`, `zqs set-setting` and `zqs delete-setting` commands. 
Closes #207
> Add zqs settings helper commands

- zsh/.zshrc
If there is still no `python` in `$PATH` after loading `~/.zshrc.pre.d`, we alias it to `python3` to keep omz from complaining.
Closes #180
> Keep omz from complaining when `python` is not in `$PATH`

- zsh/.zshrc
The `;;` was in my test directory :-/ not sure what happened
Closes #221
> Not sure how this got committed without the `;;`

- Readme.md
- zsh/.zshrc
- Convert autoload toggle file in `~` to the new settings system and add `zqs enable-zmv-autoloading` and `zqs disable-zmv-autoloading` commands to toggle it.  Closes #224
- Add `zqs-enable|disable-ssh-key-listing` commands to make it easy for users to not see a listing of loaded `ssh` keys when a new terminal session is started. Closes #227
> Add more `zqs enable|disable` commands

- zsh/.zshrc
Fix typo in function syntax from #226 commit, remove `()` from the `zsh-quickstart-check-for-ssh-askpass` function called inside the `zsh-quickstart-enable-ssh-askpass-require` function.
Closes #232
> Fixup for fetaure: enable-ssh-askpass-require

- zsh/.zshrc
After updating to the latest quickstart release, the `enable-ssh-askpass-require` option didn't work anymore like in my local tests.
Add `zsh-quickstart-set-ssh-askpass-require()` to execute if the: `zqs enable-ssh-askpass-require` has been set in the quickstart.
Refactor the check for sending the warning about a missing `ssh-askpass` application and setting the `SSH_ASKPASS_REQUIRE` variable.
Fixes #229  #233
> fixup: ssh-askpass-require

- zsh/.zshrc
The `zqs enable-ssh-askpass-require` feature created the wrong setting file name: `ssh-askpass-require`. Once enabled the ssh prompt on shell startup didn't work as the setting filename should have been named after the feature name itself: `enable-ssh-askpass-require`. Fix this error.
Fixes #237 #236
> fixup: enable-ssh-askpass-require

- Readme.md
old instructions do not work, see linked code snipped if you want to know why
https://github.com/unixorn/zsh-quickstart-kit/blob/8749b0d01ec331b1b7a0d8aa6786e9a08f7bdec0/zsh/.zshrc#L698-L703
> [FIX] Readme.md | ssh-key-listing toggle

- zsh/.zshrc
Move `ping5` function to [unixorn/jpb.zshplugin](https://github.com/unixorn/jpb.zshplugin). We want to try to keep non-quickstart functions out of the quickstart kit. This won't affect typical kit users since that plugin is part of the default list.
> Move `ping5` to jpb.zshplugin

- zsh/.zshrc
grc setup is redundant since we include warhol.plugin.zsh in the standard load.
> Remove grc setup

- Readme.md
- zsh/.zgen-setup
I've added support for a `~/.zqs-additional-plugins` file, as scripts in `~/.zshrc.pre-plugins.d/` can't access zgenom. Each line in the file will run directly as `zgenom load "$line"`
> added support for ~/.zqs-additional-plugins

- zsh/.zshrc
The previous HISTIGNORE setting doesn't
actually work per the [zsh parameters man page](https://manpages.ubuntu.com/manpages/kinetic/en/man1/zshparam.1.html)
This change implements the pattern formerly defined in HISTIGNORE.
Signed-off-by: jfmcdowell <206422+jfmcdowell@users.noreply.github.com>
Implement HISTORY_IGNORE parameter
The previous HISTIGNORE setting doesn't
actually work per the [zsh parameters man page](https://manpages.ubuntu.com/manpages/kinetic/en/man1/zshparam.1.html)
This change implements the pattern formerly defined in HISTIGNORE.
> Implement HISTORY_IGNORE parameter

- Readme.md
- zsh/.zshrc
For consistency, use `zqs disable-control-c-decorator` to keep the quickstart from displaying `^C` when the user types control-c.
This also reduces pollution in the user's environment variables.
> Deprecate `ZSH_QUICKSTART_SKIP_TRAPINT`

- Readme.md
- zsh/.zgen-setup
- zsh/.zshrc
The way to add plugins using a list file has been updated. The ability to add plugins as separate files has been added
resolves #242
> New way to add plugins

- zsh/.zshrc
- [X ] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.
This is an intital impleemntation of the 1Password ssh-agent to start the conversation on how to implement this correctly.
This code leverages the existing `can_haz` function to check for the 1Password CLI tool `op`. This is a **HUGE** assumption -- so lets talk about it.
However, I wonder if this code even needs to be merged because the user can set the [`SSH_AUTH_SOCK` environment variable](https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client) themselves in their functions file.
- [X ] A helper script
- [ X] New feature
- …
> Initial implementation of 1Password ssh-agent

- zsh/.zgen-setup
If there is an alias `ls` for the application `exa`, we get an error about the wrong argument `-A` when we run the terminal. This solution fixes the bug
> call unaliased version ls

- zsh/.zshrc
[For reasons](https://github.com/matthiasr/profile), my `~/.zshrc` is a symlink to a symlink to the quickstart kit. `readlink` only resolved one layer, causing the self-update mechanism to look at the wrong git repository.
Instead of `readlink`, which does not have portable recursive resolution, use ZSH's native [`:A` modifier][modifiers] to follow all symlinks until we find the real file, then update that.
[modifiers]: https://zsh.sourceforge.io/Doc/Release/Expansion.html#Modifiers
> selfupdate: Recursively resolve symlink

- .checkov.yml
- zsh/.zshrc
Installed Armbian on a new Orange Pi 5 and discovered that not all distros build `git` support into `exa`. Add `--git` only when `git` support is detected.
> Fix `exa` aliasing

- Readme.md
- zsh/.zshrc
Make it easy to make the quickstart not attempt to load `ssh` keys. This makes it easier for someone to store their `ssh` private keys in a yubikey.
Closes #267
> Add an option to not load `ssh` keys during session startup

- zsh/.zshrc
Added eza check and alias generation taking into account the installed application - exa or eza
In the official Exa repository it says to use the new Eza fork now. In this PR I check if `eza` is available and if it is not, I check if `exa` is installed. Then the correct aliases are formed with the correct application.
I also noticed that the environment variable `EXA_TREE_IGNORE` is not used in either `exa` or `eza`. I kept the environment variable, but changed its name to a more neutral one and passed its value explicitly to the `tree` alias call.
> Added aliases for the new "official" fork eza instead of exa

- Readme.md
- zsh/.zshrc
Make it easy to have fragment files that are only sourced on a specific OS.
> Add os-specific fragment file directories

- Readme.md
The commit adds more detailed steps for the installation and configuration of 'fzf'. It specifies the exact commands to be run and provides guidance on the prompts users might encounter, improving clarity for users unfamiliar with the process. Resolves #286
> Update 'fzf' installation instructions in Readme

- zsh/.zshrc
The function load-our-ssh-keys in zshrc has been updated to check for the existence of 1Password before setting up the ssh-agent. Now, the ssh-agent will only be initialized for 1Password if it's installed on the system. This change effectively prevents potential errors when 1Password is not available. Fixes #292
> Update ssh-agent setup for 1Password in zshrc

- zsh/.zshrc
If `$REPORTTIME` is set, leave it alone, don't overwrite it.
> Stop stepping on `REPORTTIME`

- Readme.md
- zsh/.zshrc
Load fragments from ~/.zshrc.work.d when present
> Load fragments from ~/.zshrc.work.d when present

- zsh/.zgen-setup
- zsh/.zsh_aliases
- zsh/.zsh_functions
- zsh/.zshrc
This change makes core zsh-quickstart-kit files work seamlessly when users set ZDOTDIR to a custom configuration directory, and hardens them against `setopt nounset` (error on unset parameters).
Files modified:
- zsh/.zshrc
- Replace hardcoded `~/...` paths to zsh config files with `${ZDOTDIR:-$HOME}/...`
- Guard variable tests with nounset-safe expansions (`${VAR-}`, `${VAR:-default}`, `(( ${+VAR} ))`)
- Examples:
- `~/.zqs-zprof-enabled`, `~/.zqs-debug-mode`, `~/.zqs-settings-path`, `~/.zqs-settings`
- `~/.zshrc.pre-plugins.d`, `~/.zshrc.add-plugins.d`, `~/.zshrc.d`, `~/.zshrc.$(uname).d`, `~/.zshrc.work.d`
- `~/.zgen-setup`, `~/.zsh_functions`, `~/.zsh_aliases`, `~/.sh_aliases`
- `~/.zsh/completions` cache path, `~/.zsh-completions(.d)`
- `~/.macos_aliases(.d)`, `~/.osx_aliases(.d)`
- …
> Make zsh-quickstart-kit ZDOTDIR-aware and nounset-resilient
